# Generated by Django 2.2.4 on 2019-08-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0002_empresa_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='num_telefono',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
