# Generated by Django 2.2.4 on 2019-08-13 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_bar', models.CharField(max_length=50)),
                ('logo_bar', models.URLField(blank=True, null=True)),
                ('descripcion_bar', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('url_ubicacion', models.URLField(blank=True, null=True)),
                ('horario', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=10)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_bar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ofertas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=250)),
                ('precio', models.FloatField()),
                ('imagen', models.ImageField(upload_to=None)),
                ('nombre_bar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directorio.Bares')),
            ],
        ),
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_imagen', models.URLField()),
                ('nombre_bares', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directorio.Bares')),
            ],
        ),
        migrations.CreateModel(
            name='Bebidas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=250)),
                ('precio', models.FloatField()),
                ('imagen', models.ImageField(upload_to=None)),
                ('nombre_bar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directorio.Bares')),
            ],
        ),
    ]
