# Generated by Django 2.2.4 on 2019-08-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bares',
            name='descripcion_bar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bares',
            name='horario',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bares',
            name='logo_bar',
            field=models.ImageField(blank=True, null=True, upload_to='logos'),
        ),
        migrations.AlterField(
            model_name='bares',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='bares',
            name='titulo_bar',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
