# Generated by Django 2.2.4 on 2019-08-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0002_auto_20190813_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bares',
            name='logo_bar',
            field=models.ImageField(upload_to='logos'),
        ),
        migrations.AlterField(
            model_name='bebidas',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bebidas',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenesbebidas'),
        ),
        migrations.AlterField(
            model_name='bebidas',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='imagenes',
            name='url_imagen',
            field=models.ImageField(upload_to='imagenesbares'),
        ),
        migrations.AlterField(
            model_name='ofertas',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ofertas',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenesofertas'),
        ),
        migrations.AlterField(
            model_name='ofertas',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True),
        ),
    ]
