# Generated by Django 2.2.4 on 2019-08-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0003_auto_20190813_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertas',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenofertas'),
        ),
    ]
