# Generated by Django 2.2.4 on 2019-08-13 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0004_auto_20190813_1802'),
        ('directorio', '0003_auto_20190813_1303'),
    ]

    operations = [
    ]
