# Generated by Django 2.2.4 on 2019-08-13 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0005_merge_20190813_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bebidas',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenbebidas'),
        ),
        migrations.AlterField(
            model_name='bebidas',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ofertas',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenofertas'),
        ),
        migrations.AlterField(
            model_name='ofertas',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
