# Generated by Django 2.2.4 on 2019-08-14 18:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('directorio', '0006_auto_20190813_2001'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bares',
            new_name='Bar',
        ),
    ]
