# Generated by Django 2.2.4 on 2019-08-15 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0008_auto_20190814_1827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ofertas',
            old_name='nombre_bar',
            new_name='nombre_bares',
        ),
    ]
