# Generated by Django 2.2.4 on 2019-08-15 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0009_auto_20190814_1953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ofertas',
            old_name='nombre_bares',
            new_name='nombre_bar',
        ),
    ]
