# Generated by Django 2.2.4 on 2019-08-20 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0010_auto_20190814_1954'),
        ('accounts', '0004_auto_20190814_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bar',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='directorio.Bar'),
        ),
    ]
