# Generated by Django 2.2.4 on 2019-08-20 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_bar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bar',
        ),
    ]
