# Generated by Django 2.2.4 on 2019-08-20 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0011_auto_20190820_1429'),
        ('accounts', '0006_remove_profile_bar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bar',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='directorio.Bar'),
        ),
    ]
