# Generated by Django 2.2.4 on 2019-08-20 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_profile_bar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ap_materno',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='ap_paterno',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='nombre',
        ),
    ]
